### ISSUE TITLE
socket io work only in localhost

### ISSUE THREAD

**Issue by mir161803** [priyanshrastogi/temperature-plot#1]
i already try your code, it was great at firts, it can show chart data from arduino properly on localhost:4000 but when i try to access it (localhost) with 192.168.1.3:4000 (which is the ip of my localhost laptop) from another computer i can still show the front end interface, but the moving chart didnt show and from chrome console it show error like:

polling-xhr.js:264 GET http://localhost:4000/socket.io/?EIO=3&transport=polling&t=MO6fy14 net::ERR_CONNECTION_REFUSED

**Comment by priyanshrastogi** [comment]
This is happening because the socket.io server is running on 192.168.1.3:4000 but socket.io-client is trying to connect to localhost:4000. To make it work, you must replace localhost:4000 with 192.168.1.3:4000 in index.html file.
`
var socket = io.connect('http://192.168.1.3:4000');
`
